on:
  push:
  pull_request:
  release:
    types: 
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # needed for gitversion    
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
          versionSpec: '5.2.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.2
    - name: Build solution
      run: dotnet build --configuration Release Vescon.So.WebApi.sln
    - name: Create the package
      run: dotnet pack --configuration Release --no-build Vescon.So.WebApi.sln  -o Artifacts/Packages
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2 
      if: github.event_name == 'release'
      with:
        name: nupkg
        path: 'Artifacts/Packages/**/*.nupkg'
    # - name: Publish to nuget.org
    #   run: dotnet nuget push Artifacts/Packages/**/*.nupkg --api-key ${{secrets.NUGET_ORG_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
    #   if: github.event_name == 'release'
    - name: Publish to github packages
      run: |
        for f in Artifacts/Packages/*.nupkg
        do
          echo "Uploading package: $f"
          curl -vX PUT -u "user:${{secrets.GITHUB_TOKEN}}" -F package=@$f https://nuget.pkg.github.com/vescon/
        done        
      shell: bash
      # if: github.event_name == 'release'
